-- MySQL Script generated by MySQL Workbench
-- 04/25/17 11:21:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pfe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pfe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pfe` DEFAULT CHARACTER SET utf8 ;
USE `pfe` ;

-- -----------------------------------------------------
-- Table `pfe`.`Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Option` (
  `Code` VARCHAR(45) NOT NULL,
  `Option` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Annee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Annee` (
  `Code` VARCHAR(45) NOT NULL,
  `Annee` DATE NOT NULL,
  `Etat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Promotion` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  `Nombre_etudiants` INT NOT NULL,
  `Cycle` VARCHAR(45) NOT NULL,
  `Niveau` VARCHAR(45) NOT NULL,
  `Option_Code` VARCHAR(45) NOT NULL,
  `Annee_Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Option_Code`, `Annee_Code`),
  INDEX `fk_Promotion_Option1_idx` (`Option_Code` ASC),
  INDEX `fk_Promotion_Annee1_idx` (`Annee_Code` ASC),
  CONSTRAINT `fk_Promotion_Option1`
    FOREIGN KEY (`Option_Code`)
    REFERENCES `pfe`.`Option` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Promotion_Annee1`
    FOREIGN KEY (`Annee_Code`)
    REFERENCES `pfe`.`Annee` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Section` (
  `Code` INT NOT NULL AUTO_INCREMENT,
  `Nombre_etudiants` INT NOT NULL,
  `Promotion_Numero` INT NOT NULL,
  PRIMARY KEY (`Code`, `Promotion_Numero`),
  INDEX `fk_Section_Promotion1_idx` (`Promotion_Numero` ASC),
  CONSTRAINT `fk_Section_Promotion1`
    FOREIGN KEY (`Promotion_Numero`)
    REFERENCES `pfe`.`Promotion` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Groupe` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Etudiants` INT NOT NULL,
  `Section_Code` INT NOT NULL,
  PRIMARY KEY (`Numero`, `Section_Code`),
  INDEX `fk_Groupe_Section1_idx` (`Section_Code` ASC),
  CONSTRAINT `fk_Groupe_Section1`
    FOREIGN KEY (`Section_Code`)
    REFERENCES `pfe`.`Section` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Projet` (
  `Code` VARCHAR(45) NOT NULL,
  `Titre` VARCHAR(45) NOT NULL,
  `Specialite` VARCHAR(45) NOT NULL,
  `Technologie` VARCHAR(45) NOT NULL,
  `Outil` VARCHAR(45) NOT NULL,
  `Promotion_ID` INT NOT NULL,
  `Validation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Code`, `Promotion_ID`),
  INDEX `fk_Projet_Promotion1_idx` (`Promotion_ID` ASC),
  CONSTRAINT `fk_Projet_Promotion1`
    FOREIGN KEY (`Promotion_ID`)
    REFERENCES `pfe`.`Promotion` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Equipe` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Etudiants` INT NOT NULL,
  `Moyenne` FLOAT NOT NULL,
  `Projet_Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Projet_Code`),
  INDEX `fk_Equipe_Projet1_idx` (`Projet_Code` ASC),
  CONSTRAINT `fk_Equipe_Projet1`
    FOREIGN KEY (`Projet_Code`)
    REFERENCES `pfe`.`Projet` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Etudiant` (
  `Matricule` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Sexe` VARCHAR(45) NOT NULL,
  `Date_Naissance` DATE NOT NULL,
  `Lieu_Naissance` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Willaya` VARCHAR(45) NOT NULL,
  `Moyenne` FLOAT NOT NULL,
  `Niveau` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Groupe_Numero` INT NOT NULL,
  `Equipe_Numero` INT NOT NULL,
  PRIMARY KEY (`Matricule`, `Groupe_Numero`, `Equipe_Numero`),
  INDEX `fk_Etudiant_Groupe1_idx` (`Groupe_Numero` ASC),
  INDEX `fk_Etudiant_Equipe1_idx` (`Equipe_Numero` ASC),
  CONSTRAINT `fk_Etudiant_Groupe1`
    FOREIGN KEY (`Groupe_Numero`)
    REFERENCES `pfe`.`Groupe` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiant_Equipe1`
    FOREIGN KEY (`Equipe_Numero`)
    REFERENCES `pfe`.`Equipe` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Enseignant` (
  `Matricule` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Sexe` VARCHAR(45) NOT NULL,
  `Date_Naissance` VARCHAR(45) NOT NULL,
  `Lieu_Naissance` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Willaya` VARCHAR(45) NOT NULL,
  `Specialite` VARCHAR(45) NOT NULL,
  `Grade` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Matricule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Choisir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Choisir` (
  `Etudiant_Matricule` VARCHAR(45) NOT NULL,
  `Projet_Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Etudiant_Matricule`, `Projet_Code`),
  INDEX `fk_Etudiant_has_Projet_Projet1_idx` (`Projet_Code` ASC),
  INDEX `fk_Etudiant_has_Projet_Etudiant1_idx` (`Etudiant_Matricule` ASC),
  CONSTRAINT `fk_Etudiant_has_Projet_Etudiant1`
    FOREIGN KEY (`Etudiant_Matricule`)
    REFERENCES `pfe`.`Etudiant` (`Matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiant_has_Projet_Projet1`
    FOREIGN KEY (`Projet_Code`)
    REFERENCES `pfe`.`Projet` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Seance_encadrement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Seance_encadrement` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Choisir_Etudiant_Matricule` VARCHAR(45) NOT NULL,
  `Choisir_Projet_Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Choisir_Etudiant_Matricule`, `Choisir_Projet_Code`),
  INDEX `fk_Seance_encadrement_Choisir1_idx` (`Choisir_Etudiant_Matricule` ASC, `Choisir_Projet_Code` ASC),
  CONSTRAINT `fk_Seance_encadrement_Choisir1`
    FOREIGN KEY (`Choisir_Etudiant_Matricule` , `Choisir_Projet_Code`)
    REFERENCES `pfe`.`Choisir` (`Etudiant_Matricule` , `Projet_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Appriciation_Global`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Appriciation_Global` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  `Note_livrable` FLOAT NOT NULL,
  `Note_Logiciel` FLOAT NOT NULL,
  `Equipe_Numero` INT NOT NULL,
  `Seance_encadrement_Numero` INT NOT NULL,
  PRIMARY KEY (`Numero`, `Equipe_Numero`, `Seance_encadrement_Numero`),
  INDEX `fk_Appriciation_Global_Equipe1_idx` (`Equipe_Numero` ASC),
  INDEX `fk_Appriciation_Global_Seance_encadrement1_idx` (`Seance_encadrement_Numero` ASC),
  CONSTRAINT `fk_Appriciation_Global_Equipe1`
    FOREIGN KEY (`Equipe_Numero`)
    REFERENCES `pfe`.`Equipe` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appriciation_Global_Seance_encadrement1`
    FOREIGN KEY (`Seance_encadrement_Numero`)
    REFERENCES `pfe`.`Seance_encadrement` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Appriciation_indv_assiduite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Appriciation_indv_assiduite` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  `Note_logiciel` FLOAT NOT NULL,
  `Note_livrable` FLOAT NOT NULL,
  `Assuidite` VARCHAR(45) NOT NULL,
  `Note_generale` VARCHAR(45) NULL,
  `Etudiant_Matricule` VARCHAR(45) NOT NULL,
  `Seance_encadrement_Numero` INT NOT NULL,
  PRIMARY KEY (`Numero`, `Etudiant_Matricule`, `Seance_encadrement_Numero`),
  INDEX `fk_Appriciation_indv_assiduite_Etudiant1_idx` (`Etudiant_Matricule` ASC),
  INDEX `fk_Appriciation_indv_assiduite_Seance_encadrement1_idx` (`Seance_encadrement_Numero` ASC),
  CONSTRAINT `fk_Appriciation_indv_assiduite_Etudiant1`
    FOREIGN KEY (`Etudiant_Matricule`)
    REFERENCES `pfe`.`Etudiant` (`Matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appriciation_indv_assiduite_Seance_encadrement1`
    FOREIGN KEY (`Seance_encadrement_Numero`)
    REFERENCES `pfe`.`Seance_encadrement` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Salle` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Soutenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Soutenance` (
  `Code` VARCHAR(45) NOT NULL,
  `Jour` DATE NOT NULL,
  `Heure` TIME NOT NULL,
  `Note` FLOAT NOT NULL,
  `Projet_Code` VARCHAR(45) NOT NULL,
  `Salle_Numero` INT NOT NULL,
  PRIMARY KEY (`Code`, `Projet_Code`, `Salle_Numero`),
  INDEX `fk_Soutenance_Projet1_idx` (`Projet_Code` ASC),
  INDEX `fk_Soutenance_Salle1_idx` (`Salle_Numero` ASC),
  CONSTRAINT `fk_Soutenance_Projet1`
    FOREIGN KEY (`Projet_Code`)
    REFERENCES `pfe`.`Projet` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soutenance_Salle1`
    FOREIGN KEY (`Salle_Numero`)
    REFERENCES `pfe`.`Salle` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Jury`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Jury` (
  `Numero` INT NOT NULL,
  `Soutenance_Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Soutenance_Code`),
  INDEX `fk_Jury_Soutenance1_idx` (`Soutenance_Code` ASC),
  CONSTRAINT `fk_Jury_Soutenance1`
    FOREIGN KEY (`Soutenance_Code`)
    REFERENCES `pfe`.`Soutenance` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Adminstrateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Adminstrateur` (
  `Matricule` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Sexe` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Date_naissance` DATE NOT NULL,
  `Lieu_naissance` VARCHAR(45) NULL DEFAULT NULL,
  `Willaya` VARCHAR(45) NULL DEFAULT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Matricule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Parametre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Parametre` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nbr_max` INT NOT NULL,
  `Nbr_min` INT NOT NULL,
  `Affection_mode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pfe`.`Proposer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pfe`.`Proposer` (
  `Enseignant_Matricule` VARCHAR(45) NOT NULL,
  `Projet_Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Enseignant_Matricule`, `Projet_Code`),
  INDEX `fk_Enseignant_has_Projet_Projet1_idx` (`Projet_Code` ASC),
  INDEX `fk_Enseignant_has_Projet_Enseignant1_idx` (`Enseignant_Matricule` ASC),
  CONSTRAINT `fk_Enseignant_has_Projet_Enseignant1`
    FOREIGN KEY (`Enseignant_Matricule`)
    REFERENCES `pfe`.`Enseignant` (`Matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enseignant_has_Projet_Projet1`
    FOREIGN KEY (`Projet_Code`)
    REFERENCES `pfe`.`Projet` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
